Edição da anamnese gigante
dev-ox/Saudox pull request #109
Opened 2020-10-17 20:47 UTC by Sekva

Ajustes foram precisos na classe anonima

2020-10-17 20:49 UTC, Sekva commented
Também removi as definições de old do arquivo de criar

2020-10-18 21:39 UTC, MBaltz commented on Saudox/app/AnamneseGigantePsicopedaNeuroPsicomoto.php
>          $anamnese_proxy = new class($pt1_pt2_pt3) {
### Ficou parecendo uma classe Java kkkjds

2020-10-18 23:26 UTC, MBaltz requested changes
## TrabalhÃO, ficou muito bom.
### Algumas mudanças foram requisitadas

2020-10-18 23:26 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/psicopedagogia/editar.blade.php
> +                            <input type="number" name="idade_gestacional_do_bebê_ao_nascer" value="{{ g_old($anamnese, "idade_gestacional_do_bebê_ao_nascer") }}" />
### Realizar a remoção do acento circunflexo em bebê
__Lembrar: fazer a alteração em todo o projeto, onde esse nome é encontrado__

2020-10-18 23:26 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/psicopedagogia/editar.blade.php
> +                            <input type="text" name="serie_e_turno" value="{{ g_old($anamnese, "serie_e_turno") }}" />
## Criar na na seed de anamnese esse campo
### OBS: é na pt2, em cima de 'professor', caso queira deixar organizado

2020-10-18 23:26 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/psicopedagogia/editar.blade.php
> +                            <label>Sabe dias da semana</label><input value="Sabe dias da semana" type="checkbox" name="conhece_tais_coisas[]" id="mesmo_sexo" {{ g_in_array_old($anamnese, "Sabe dias d
### Testado e funcionando, muito bom!

2020-10-18 23:26 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/psicopedagogia/editar.blade.php
> +<link href="{{ asset('css/form_pag.css') }}" rel="stylesheet">
# Como principal mudança:
## Colocar o botão de salvar o formulário partindo de qualquer página da criação da anamnese.
__Uma sugestão de onde colocar seria em baixo dos botões de passar pa a próxima página__

2020-10-19 05:50 UTC, MBaltz commented
## Lembrar de colocar o asterisco na view de criar e editar nos campos obrigatórios
@Sekva

2020-10-19 06:26 UTC, MBaltz approved these changes
# Ótimo trabalho!

2020-10-19 06:27 UTC, merged

2020-10-19 07:42 UTC, MBaltz commented
[#174990148]