Ajustes nas views de anamnese e avaliação (e na home de paciente rs)
dev-ox/Saudox pull request #120
Opened 2020-10-23 20:25 UTC by mrjonio

- Espaçamento das views
- Campos que extrapolam certos limites
- Tabela na avaliação de judô (ficou mais bonita e padronizada com o resto do projeto)
- Botões na home de paciente (alguem havia desconfigurado eles)

2020-10-23 23:13 UTC, MBaltz requested changes
## Não entendi o pullrequest

2020-10-23 23:13 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
> +                <div class="info-pessoal">
## Oi Carlos. Não consegui perceber diferenças nas views de 'ver', mesmo com um pullrequest tão GRANDE. Tentei buscar por essa classe css, mas não achei.....

2020-10-23 23:14 UTC, mrjonio commented on Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
> +                <div class="info-pessoal">
A classe já estava no projeto, ela veio com o pull request da PNP.
A diferença é justamente aquele espaçamento que eu disse hoje (que ia fazer depois)

2020-10-23 23:26 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
> +                <div class="info-pessoal">
Não sei se estou com problemas para achar essa classe, mas ja procurei no próprio github, nos arquivos css e no atom com a busca avançada, mas não achei.

2020-10-24 00:00 UTC, mrjonio commented on Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
> +                <div class="info-pessoal">
Ahhh entendi agora. De fato, essas classes ai não existem, eu utilizei só pra demarcar o conteúdo do div.
Eventualmente eu comecei a copiar as estruturações do HTML (pra agilizar as coisas) e as classes vinham junto... São inofensivas, mas qualquer coisa, dá pra tirar dps :3

2020-10-24 00:03 UTC, MBaltz commented on Saudox/resources/views/profissional/anamnese/fonoaudiologia/ver.blade.php
> +                <div class="info-pessoal">
Entendido! 
Agora vou dormir feliz, pesquisei em todos os cantos, fui buscar no PR que tu falou tmb kjdsds

2020-10-24 00:03 UTC, merged