Finalização seeds dados reais
dev-ox/Saudox pull request #125
Opened 2020-10-26 18:07 UTC by ednaldoj

-Ajustes no campo observações profissional;
-Seeds dados reais anamnese fonoaudiologia;
-Seeds dados reais anamnese gigante;
-Seeds dados reais anamnese terapia ocupacional;
-Seeds dados reais avaliação fonoaudiologia;
-Seeds dados reais avaliação judô;
-Seeds dados reais avaliação terapia ocupacional;
-Seeds dados reais avaliação neuropsicológica

2020-10-27 21:24 UTC, MBaltz requested changes
## As seeds não executaram, pois há alguns erros.
### Lembrar de testar as seeds antes de criar o pullrequest

2020-10-27 21:24 UTC, MBaltz commented on Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
> +                'id_anaminese' => rand(1,$qtd_anamnese_gigante),
## Esse campo nem se quer existe mais.
### As seeds rodaram no seu computador normalmente?

2020-10-28 17:21 UTC, ednaldoj commented on Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
> +                'id_anaminese' => rand(1,$qtd_anamnese_gigante),
Qual a mensagem de erro que apareceu? Aqui executaram normalmente.

2020-10-28 17:34 UTC, MBaltz commented on Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
> +                'id_anaminese' => rand(1,$qtd_anamnese_gigante),
> Qual a mensagem de erro que apareceu? Aqui executaram normalmente.

```bash
  1   PDOException::("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_anaminese' in 'field list'")
      /home/baltz/Downloads/apagar/fork_ednaldo/Saudox/Saudox/vendor/laravel/framework/src/Illuminate/Database/Connection.php:457
```
### Execute os seguintes comandos para testar as seeds:
```bash
$ composer dump-autoload
$ php artisan migrate:fresh --seed
```

2020-10-28 17:37 UTC, MBaltz commented on Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
> +                'id_anaminese' => rand(1,$qtd_anamnese_gigante),
### Model referido: `avaliacao__neuropsicologicas`

2020-10-28 17:54 UTC, ednaldoj commented on Saudox/database/seeds/AvaliacaoNeuropsicologicasAutSeeds.php
> +                'id_anaminese' => rand(1,$qtd_anamnese_gigante),
Resolvido ;D

2020-10-28 18:17 UTC, MBaltz requested changes
## Mudanças requisitadas, pois faltam alguns campos no processo de população do banco

2020-10-28 18:17 UTC, MBaltz commented on Saudox/database/seeds/AnamnesePsicopedaNeuroPsicomotosPt3AutSeeds.php
>              ]);
## Pude perceber nessa e em outros formulários, que nem todos os campso estão sendo preenchidos.
### Por exemplo, nessa Anamnese PNP parte 3, existem os campos:
```php
            $table->text('analise_da_entrevista')->nullable(true);
            $table->text('encaminhamentos')->nullable(true);
````
### e estes não constam na seed. 
### Ademais, não são só esses dois campso que faltam. Em outros formulários esse erro também é presente.

---

## Para auxiliar no processo de resolução desse problema, sugiro inicialmente popular o banco de dados, abrir o servidor e verificar em cada formulário na view de editar. Se o dado campo não estiver sendo preenchido automaticamente, verifique se estes estão com as seeds ok.
Ademais, também realizar essa verificação para os outros models (paciente, profissional, agendamentos, etc)

2020-10-28 18:19 UTC, MBaltz commented
## Está fazendo um trabalho muito bom.
@ednaldoj

2020-10-28 18:22 UTC, MBaltz commented
### Outra pequena observação para mudança:
Esse campo é de texto, donde o valor pode ser ou `Pública` ou `Privada`
![image](https://user-images.githubusercontent.com/25617786/97479692-45331680-1931-11eb-9bd9-974c207fbaca.png)

2020-10-28 22:56 UTC, MBaltz commented
## Fez um trabalho muito bom :+1:

2020-10-28 22:57 UTC, merged