Criacao questionario ava fono para crianças de 12 a 17 meses [editar pra por o id do pivotal quando organizar a historia]
dev-ox/Saudox pull request #128
Opened 2020-10-27 04:50 UTC by Sekva

Criação e visualização apenas

2020-10-27 23:07 UTC, MBaltz requested changes
## Requisição de mudanças foram realizadas
### Basicamente são mudanças super pequenas, mais relacionadas a acentuação e ordem de apresentação  de alguns campos

2020-10-27 23:07 UTC, MBaltz commented on Saudox/resources/views/profissional/avaliacao/fonoaudiologia/criar.blade.php
> +            <!-- o finalzinho parece ser só exemplos.... -->
## Nesse caso faltou colocar o indicativo de cada palavra que o profissional irá repetir, baseando-se no exemplo citado acima (Ex.: Olhe a bola... bola)
### Sugiro colocar um label bem simples, em baixo do `Ex.:`, com os seguintes elementos dentro de parenteses:
`(bola, neném, carro, papai e mamãe)`

![image](https://user-images.githubusercontent.com/25617786/97370751-80303e00-188e-11eb-98f4-9a21d5970ac8.png)

2020-10-27 23:07 UTC, MBaltz commented on Saudox/resources/views/profissional/avaliacao/fonoaudiologia/criar.blade.php
> +            <!-- o finalzinho parece ser só exemplos.... -->
```suggestion
            Ex.: Olhe a bola....bola <br>
            (bola, neném, carro, papai e mamãe) <br>
```

2020-10-27 23:07 UTC, MBaltz commented on Saudox/resources/views/profissional/avaliacao/fonoaudiologia/ver.blade.php
> +@extends('layouts.mainlayout')
# Todas as modificações nos textos aplicadas na view de criar, deverão ser feitas na view de ver.

2020-10-27 23:07 UTC, MBaltz commented on Saudox/resources/views/profissional/avaliacao/fonoaudiologia/criar.blade.php
> +@extends('layouts.mainlayout')
# !aviso!
# Todas as modificações nos textos aplicadas na view de criar, deverão ser feitas na view de ver.

2020-10-27 23:15 UTC, Sekva commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
> +            'avaliacao' => NULL,
sim, pra ser o mínimo de diferença possível pra view editar

2020-10-27 23:20 UTC, Sekva commented on Saudox/resources/views/profissional/avaliacao/fonoaudiologia/criar.blade.php
> +                        <input value="{{ g_old($avaliacao, "data_avaliacao") }}" type="date" name="data_avaliacao" id="data_avaliacao">
exato, e talvez nem tudo seja feito na frente do computador, em um dia ou hora diferente, não existe obrigação nenhuma dessa data ser a criação no sistema. se for, nem precisa do campo, já que todo model tem o time stamp

2020-10-28 02:18 UTC, MBaltz commented
## Parabéns pelo trabalho.
### Ficou muito organizado, bem fiel ao documento.

2020-10-28 02:19 UTC, merged