Alguns ajustes da ultima release
dev-ox/Saudox pull request #65
Opened 2020-09-21 03:14 UTC by Sekva

- Estava sendo mostrado agendamentos concluídos/cancelados na home do profissional
- O agendamento está sendo usado como base para completar o cadastro do paciente
- Desligando testes desnecessários
- Reescrevendo alguns testes
  - Testes de cadastro de profissional ok (tinha problemas na criação do profissional que se ia logar)
  - Testes de cadastro de paciente ainda faltam serem reescritos

2020-09-21 17:18 UTC, Sekva commented
Não aceitar ainda, vou trabalhar mais nesse PR

2020-09-21 23:24 UTC, Sekva commented
Testes reajustados e prontos pra uso.

2020-09-22 00:31 UTC, MBaltz requested changes
# A escrita de código está muito boa. Parabéns.
## Código muito organizado e prático, evitando repetições.

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        /*
## Deve ser porque não está sendo aplicado o hash na senha. Ademais, parabéns pela ideia.
__Sugestão: Tentar resolver esse processo do login para finalizar o teste e deixar ele bem completo. Nesse cado, aplicando o hash no factory resolveria.__

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +    /* TODO: endereço é um teste pra cada campo.... e não usar id_endereco */
## Nesse sentido, deve-se criar um arquivo apenas para teste de Endereço, o que acha da ideia? Aí reolveria os testes tanto pra Paciente quando para Profissional.

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: acho que vai mais coisa aqui */
## Complementar esse teste:
- Redirecionar para 'paciente.home'
- Verificar que ele foi redirecionado para 'login' ou que não não foi redirecionado para 'paciente.home'

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +        $this->assertCount($num_funcionarios, Profissional::all());
## Ótimo!

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +        $this->assertCount($num_funcionarios, Profissional::all());
Esse esquema do $num_func

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +    /** @ test **/
## Pensar no uso de um arquivo 'CadastroEndereçoProfissional' e 'CadastroEndereçoPaciente'

2020-09-22 00:31 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +    /* TODO: verificar esses 4 numeros... */
## Ja realizei uma busca pela internet, é muito difícil encontrar algum tipo de informação de padronização do número com conselho, já que pode mudar de estado pra estado. Inclusive, nada impede de conter letras.

2020-09-22 00:33 UTC, Sekva commented on Saudox/phpunit.xml
> +        <server name="DB_DATABASE" value=":memory:"/>
Nop, mas acho que é alto, visto que o actions é pra ser uma coisa rápida, então devem disponibilizar um bucado por um curto periodo de tempo.

2020-09-22 00:33 UTC, Sekva commented on Saudox/app/Agendamentos.php
> +        'email' => 'email',
(-‿◦☀)

2020-09-22 00:35 UTC, Sekva commented on Saudox/resources/views/profissional/criar_paciente.blade.php
> +                        <input value="{{ old('cpf', $agendamento->cpf) }}" class="noscroll" onkeypress='validar_apenas_numeros(event)' placeholder="CPF (apenas números)" type="number"  name="cpf" id=
o segundo argumento é o fallback, old('nome_paciente') tá vazio? pega $agendamento->nome, mesmo que esteja vazio. assim dá pra manter o redirect()->back()->withInput();

2020-09-22 00:37 UTC, Sekva commented on Saudox/resources/views/profissional/home.blade.php
> +                            <a class="btn-paciente bordas_amarelas"  href={{route('profissional.criar_paciente', $agenda[0]->id) }}>Registrar Cliente</a>
Parece que antes tinha, não lembro bem, lembrar de colocar essa opção junto embaixo de criar profissional.

2020-09-22 00:39 UTC, Sekva commented on Saudox/database/factories/AgendamentosFactory.php
> +        'data_nascimento_paciente' => date('d-m-Y'),
ele reformata pro bd, nos testes, o unico lugar onde a factory é pra ser usada. coloquei esse formato pra ficar mais legivel caso algum problema, mas funciona sem problemas assim

2020-09-22 00:39 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +    /* TODO: endereço é um teste pra cada campo.... e não usar id_endereco */
exatamente isso

2020-09-22 00:41 UTC, Sekva commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +        $this->assertCount($num_funcionarios, Profissional::all());
depois eu tive que refatorar umas coisas, e ficou dispensável fazer assim, já que o db é zerado antes de cada função

2020-09-22 00:41 UTC, Sekva commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +    /** @ test **/
yep

2020-09-22 00:41 UTC, Sekva commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +    /* TODO: verificar esses 4 numeros... */
deixar livre então?

2020-09-22 00:43 UTC, Sekva commented on Saudox/database/factories/AgendamentosFactory.php
> +        'data_saida' => Carbon::now(),
a factory empurra direto no db, não tem validação nenhuma a não ser a do db. quanto a essa carbon::now(), funciona sem problemas e a data fica no formato padrao no db

2020-09-22 00:44 UTC, Sekva commented on Saudox/tests/Feature/AnamneseTest.php
> +    /** @ test **/
sim, tem duas formas de dizer uma função de teste, começar o nome da função com testCoisaTestada(), ou anotar assim com /** @test **/.
fazendo assim é como dizer que essa não é uma função de teste, mas deixa facil "ligar" de novo

2020-09-22 00:44 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +            'remember' => 'on',
nem faz diferença no final asiodahsduha

2020-09-22 00:45 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +    private function loginProfisssional() : void {
retorna void, algumas funções tem que ficar explicita o tipo de retorno, pra mim facilita a escrever mais rapido que o nvim completa

2020-09-22 00:46 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        $this->assertTrue(Auth::check());
o $this->assertAuthenticatedAs($p) só funciona se tiver logado nesse esquema ai do Auth

2020-09-22 00:47 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        ]);
foi o padrao que carlos deixou, acho que fazendo assim explicita sempre a senha, já que uma vez hasheada, fica mais dificil achar ela, não existe uma "variavel local" pra usar, acho que foi isso

2020-09-22 00:50 UTC, Sekva commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        /*
a factory nesse caso não resolve, já que a gente nesse teste ta preenchendo um formulario do paciente na view e enviando o post, e não empurrando um paciente já ok no bd

2020-09-22 01:01 UTC, MBaltz commented on Saudox/database/factories/AgendamentosFactory.php
> +        'data_nascimento_paciente' => date('d-m-Y'),
Okay!

2020-09-22 01:01 UTC, MBaltz commented on Saudox/resources/views/profissional/home.blade.php
> +                            <a class="btn-paciente bordas_amarelas"  href={{route('profissional.criar_paciente', $agenda[0]->id) }}>Registrar Cliente</a>
Okay!

2020-09-22 01:01 UTC, MBaltz commented on Saudox/resources/views/profissional/criar_paciente.blade.php
> +                        <input value="{{ old('cpf', $agendamento->cpf) }}" class="noscroll" onkeypress='validar_apenas_numeros(event)' placeholder="CPF (apenas números)" type="number"  name="cpf" id=
Okay!

2020-09-22 01:02 UTC, MBaltz commented on Saudox/phpunit.xml
> +        <server name="DB_DATABASE" value=":memory:"/>
Okay!

2020-09-22 01:03 UTC, MBaltz commented on Saudox/database/factories/AgendamentosFactory.php
> +        'data_saida' => Carbon::now(),
## Perfeito, ótima então!
### Isso exige da gente mais atenção quanto as informações colocadas nos testes.

2020-09-22 01:03 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +            'remember' => 'on',
## assim como a maioria dos detalhes na vida ksjjkdjdksjd

2020-09-22 01:05 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +    private function loginProfisssional() : void {
jsdksjk
### Entendido

2020-09-22 01:06 UTC, MBaltz commented on Saudox/tests/Feature/AnamneseTest.php
> +    /** @ test **/
## Concordo plenamente.
Esse coisa do ascii foi curiosidade, pra saber qual era o número na tabela, aí tasquei ai

2020-09-22 01:07 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        $this->assertTrue(Auth::check());
## Quero ver o cara não estar logado no teste. Logo 3 verificação diferete

2020-09-22 01:14 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        ]);
@Sekva 
## Tudo bem. Um indicativo de recomendação é aplicar o hash direto no factory, e só 'colocar' a senha '123123123' no ato do login, nos testes.
### Exemplo:
```php
       public function pacientePodeLogarComDadosCorretos() {
        $resposta = $this->post(route('login'), [
            'login' => $paciente->login,
            'password' => '123123123',
        ]);

        $resposta->assertRedirect(route('paciente.home'));
        $this->assertAuthenticatedAs($paciente);
    }
```
ao invés de
```php
       public function pacientePodeLogarComDadosCorretos() {
        $paciente = factory(Paciente::class)->create([
            'password' => bcrypt($password = '123123123'),
        ]);

        $resposta = $this->post(route('login'), [
            'login' => $paciente->login,
            'password' => $password,
        ]);

        $resposta->assertRedirect(route('paciente.home'));
        $this->assertAuthenticatedAs($paciente);
    }
```

2020-09-22 01:15 UTC, MBaltz commented on Saudox/tests/Feature/CadastroClienteTest.php
> +        /*
## Compreendido

2020-09-22 01:15 UTC, Sekva commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: acho que vai mais coisa aqui */
complementado

2020-09-22 01:16 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +        $this->assertCount($num_funcionarios, Profissional::all());
### Hmm. Entendi.

2020-09-22 01:16 UTC, MBaltz commented on Saudox/tests/Feature/CadastroProfissionalTest.php
> +    /* TODO: verificar esses 4 numeros... */
## Isso mesmo.

2020-09-22 01:26 UTC, MBaltz requested changes
## Apenas o redirecionamento da rota que está para a home ao invés do perfil.

2020-09-22 01:26 UTC, MBaltz commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: mudar pra rota de ter perfil quando existir */
## Acho que o correto é ficar na home mesmo, pois lá vai aparecer as infos das anamneses, avaliações e evoluções, tendeu?

2020-09-22 01:26 UTC, MBaltz commented on Saudox/tests/Feature/LoginPacienteTest.php
>          $resposta->assertRedirect(route('paciente.home'));
## Nesse caso, faltou redirecioná-lo para paciente.perfil. Como o nome do método diz.

2020-09-22 01:28 UTC, Sekva commented on Saudox/tests/Feature/LoginPacienteTest.php
>          $resposta->assertRedirect(route('paciente.home'));
não existe, colocar paciente.perfil causaria um erro, e não uma falha. a gente só pode colocar paciente.perfil quando a rota exisitir. a rota que existe é agora é rota do profissional ver o paciente

2020-09-22 01:29 UTC, Sekva commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: mudar pra rota de ter perfil quando existir */
2 comment na mesma linha??

2020-09-22 01:29 UTC, MBaltz commented
## Ótima codificação! 
__Grande evolução também!__

2020-09-22 01:29 UTC, merged

2020-09-22 01:29 UTC, Sekva commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: mudar pra rota de ter perfil quando existir */
![image](https://user-images.githubusercontent.com/25044856/93836680-eefbf500-fc59-11ea-95b7-0da2ef25d579.png)

2020-09-22 01:30 UTC, MBaltz commented on Saudox/tests/Feature/LoginPacienteTest.php
>          $resposta->assertRedirect(route('paciente.home'));
## Erro meu, está tudo certinho.

2020-09-22 01:30 UTC, MBaltz commented on Saudox/tests/Feature/LoginPacienteTest.php
> +        /* TODO: mudar pra rota de ter perfil quando existir */
## Erro meu, está tudo certinho.