[#174990139] Editar avaliação terapia ocupacional
dev-ox/Saudox pull request #93
Opened 2020-10-08 03:55 UTC by mrjonio

- Edição da avaliação de terapia ocupacional
- Mudei a forma como a data era adquirida na tela de criação

2020-10-09 05:28 UTC, MBaltz commented
## Essa revisão será feita após a entrega dessa próxima release, pois trata-se de algo que não está no escopo da release atual

2020-10-10 16:53 UTC, Sekva requested changes

2020-10-10 16:53 UTC, Sekva commented on Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/editar.blade.php
> +    }
Não precisa tirar essas funções, só adiciona um TODO pra mudar essas funções pra as funções em escopo global.

2020-10-10 16:53 UTC, Sekva commented on Saudox/resources/views/profissional/avaliacao/terapia_ocupacional/editar.blade.php
> +                        <textarea class="textareas_form" id="info_extras_relevante" name="info_extras_relevante" rows="4" cols="50" style="">{{$avaliacao->info_extras_relevante}}</textarea><br><br>
Aqui e em varios lugares desse arquivo, tu usa só usando o objeto. A ideia é substituir 
de
`{{$avaliacao->info_extras_relevante}}`
para
`{{ old2($avaliacao, "info_extras_relevante") }}`

Fazendo isso, mantém salvo qualquer informação já editada caso de algum erro de validação

2020-10-13 01:01 UTC, Sekva approved these changes
Tudo nice, bom trabalho, tamo perto （ΦωΦ）

2020-10-13 01:01 UTC, merged