Verificando já existência de avaliações e anamneses
dev-ox/Saudox pull request #99
Opened 2020-10-13 22:16 UTC by Sekva

Não usei o redirect()->back(), já que a anamnese existindo, a única
forma de chegar no formulário é editando a url, e quem for fazer isso já
faz com más intenções, então deixa a pessoa ter o trabalho de preencher
e perder todo esse trabalho. A gente não precisa se importar com a
usabilidade de quem quer usar o sistema errado.

	On branch multiplas_criacoes_ana_ava
	Changes to be committed:
		modified:   app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
		modified:   app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php

2020-10-14 11:55 UTC, mrjonio approved these changes

2020-10-14 11:55 UTC, mrjonio commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
> +        if($anamnese_t){
Perfeito, eu tinha pensado em impedir completamente a possibilidade de acessar a url caso a avaliação/anamnese já tivesse sido cadastrada, mas isso é bem melhor sihasfasf

2020-10-14 11:55 UTC, mrjonio commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAvaliacaoController.php
> +        if($avaliacao_t){
A minha única ressalva seria mudar a mensagem de erro, ao invés de exibir o id do paciente, exibe só o resto da mensagem.

2020-10-15 02:32 UTC, MBaltz requested changes

2020-10-15 02:32 UTC, MBaltz commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
> +            return redirect()->route('erro', ['msg_erro' => "Paciente " .$entrada['id_paciente']. " inexistente"]);
## O mesmo comentário de Carlos cabe aqui.
### No entanto, ao invés de colocar o id do paciente, poderia ser o seu nome.

2020-10-15 02:34 UTC, Sekva commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
> +            return redirect()->route('erro', ['msg_erro' => "Paciente " .$entrada['id_paciente']. " inexistente"]);
Como vai ser o nome do paciente que não existe? kkkkkkkk

2020-10-15 02:34 UTC, mrjonio commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
> +            return redirect()->route('erro', ['msg_erro' => "Paciente " .$entrada['id_paciente']. " inexistente"]);
Eu acho que não precisa colocar o nome, já que essa parte ai seria caso o paciente **não exista**, e como Machado mesmo disse, quando alguem acessa essas rotas editando na url, já faz na malicia, então é melhor n dar nem o nome

2020-10-15 02:36 UTC, MBaltz commented on Saudox/app/Http/Controllers/Profissional/ProfissionalAnamneseController.php
> +            return redirect()->route('erro', ['msg_erro' => "Paciente " .$entrada['id_paciente']. " inexistente"]);
Então basta remover esse id dessa msg de erro. Acho que passou despercebida

2020-10-15 02:36 UTC, merged